
const DOCUMENTS = require('../util/constants.json').documents.type;

module.exports ={
    "type" : DOCUMENTS.sectors,
    "data" : [
      {"name" : "Accounting", "desc" : ""},
      {"name" : "Advertising", "desc" : ""},
      {"name" : "Aerospace", "desc" : ""},
      {"name" : "Agriculture & Agribusiness", "desc" : ""},
      {"name" : "Air Transportation", "desc" : "" },
      {"name" : "Apparel & Accessories"},
      {"name" : "Auto", "desc" : ""},
    	{"name" : "Banking", "desc" : ""},
    	{"name":"Beauty & Cosmetics", "desc" : ""},
    	{"name" : "Biotechnology", "desc" : ""},
    	{"name" : "Chemical", "desc" : ""},
    	{"name" : "Communications", "desc" : ""},
    	{"name" : "Computer", "desc" : ""},
    	{"name" : "Construction", "desc" : ""},
    	{"name" : "Consulting" , "desc" : ""},
    	{"name" : "Consumer Products", "desc" : ""},
    	{"name" : "Education", "desc" : ""},
    	{"name" : "Electronics", "desc" : ""},
    	{"name" : "Employment", "desc" : ""},
    	{"name" : "Energy" , "desc" : ""},
    	{"name" : "Entertainment & Recreation", "desc" : ""},
    	{"name" : "Fashion", "desc" : ""},
    	{"name" : "Financial Services", "desc" : ""},
    	{"name": "Fine Arts", "desc" : ""},
    	{"name": "Food & Beverage", "desc" : ""},
    	{"name": "Green Technology", "desc" : ""},
    	{"name": "Health", "desc" : ""},
    	{"name": "	Information", "desc" : ""},
    	{"name": "Information Technology", "desc" : ""},
    	{"name": "Insurance", "desc" : ""},
    	{"name": "Journalism & News", "desc" : ""},
    	{"name": "Legal Services", "desc" : ""},
    	{"name": "Manufacturing", "desc" : ""},
    	{"name": "Media & Broadcasting", "desc" : ""},
    	{"name": "Medical Devices & Supplies", "desc" : ""},
    	{"name": "Motion Pictures & Video", "desc" : ""},
    	{"name": "Music", "desc" : ""},
    	{"name": "Pharmaceutical", "desc" : ""},
    	{"name": "Public Relations", "desc" : ""},
    	{"name": "Publishing", "desc" : ""},
    	{"name": "Real Estate", "desc" : ""},
    	{"name": "Retail", "desc" : ""},
    	{"name": "Service", "desc" : ""},
    	{"name": "Sports", "desc" : ""},
    	{"name": "Technology", "desc" : ""},
    	{"name": "Telecommunications", "desc" : ""},
    	{"name": "Tourism", "desc" : ""},
    	{"name": "Transportation", "desc" : ""},
    	{"name": "Travel", "desc" : ""},
    	{"name": "Utilities", "desc" : ""},
    	{"name": "Video Game ", "desc" : ""},
    	{"name": "Web Services", "desc" : ""}
  ]
};

console.log(module.exports);
